[package]
name = "event-stream"
version = "0.1.1"
edition = "2025"

[dependencies]
common = { path = "../common" }
rdkafka = { version = "0.36", features = ["cmake-build"] }
thiserror = "1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
